### ISSUE TITLE
docker-compose example for a public setup (SSL, FQDN, pw protected)

### ISSUE THREAD

**Issue by Helmi** [adriankumpf/teslamate#153]
Hey everyone,

not sure if we're supposed to post example setups here but in absence of a better place to do so I thought I'd just do it ;)

This is what currently works for me as a publicly reachable setup. Publicly reachable here means it's installed on a VPS that is out in the open. So if you use this setup be aware of that.

**What is differentl:**

 - everything sits behind a reverse proxy that also acts as an SSL terminator (Traefik)
 - some services are renamed
 - every custom setting in the compose file is put to an env file
 - everything publicly accessible uses an FQDN (Fully qualified domain name) and automatically acquires a Let's Encrypt certificate.

**What you need to do before running it:**

 - Setup your custom stuff in the .env file and put it in the same directory as the docker-compose.yml
 - create a directory called 'acme' in the same directory. this is where your SSL cert information will be stored
 - create a .htpasswd file in your directory containing user and password for the teslamate settings access. You can do it on the web if you don't have apache tools installed (e.g. http://www.htaccesstools.com/htpasswd-generator/)

**What is still to be done:**

 - Mosquitto isn't publicly reachable (as I don't need it to be). I don't use it all though so I'm not even sure if it needs to be accessible.

_docker-compose.yml_
```YAML
version: '3'

networks:
  proxynet:
    driver: bridge
  webgateway:
    external: true

services:
  teslamate:
    image: teslamate/teslamate:latest
    restart: unless-stopped
    depends_on:
      - database
    environment:
      - DATABASE_USER=${TM_DB_USER}
      - DATABASE_PASS=${TM_DB_PASS}
      - DATABASE_NAME=${TM_DB_NAME}
      - DATABASE_HOST=database
      - MQTT_HOST=mosquitto
      - VIRTUAL_HOST=${FQDN_TM}
      - TZ={$TM_TZ}
    networks:
      - proxynet  
    ports:
      - 4000
    cap_drop:
      - all
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=${COMPOSE_PROJECT_NAME}_proxynet' # you need to change pd_ to something else if you use a different stack name when starting
      - 'traefik.port=4000'
      - 'traefik.backend=teslamate'
      - 'traefik.backend.loadbalancer.method=drr'
      - 'traefik.frontend.rule=Host:${FQDN_TM}' # change this to your hostname. That hostname needs to point to your server
      - 'traefik.domain=${FQDN_TM}' # change this to your hostname. That hostname needs to point to your server
      - 'traefik.frontend.auth.basic.usersFile=/auth/.htpasswd'

  database:
    image: postgres:11
    environment:
      - POSTGRES_USER=${TM_DB_USER}
      - POSTGRES_PASSWORD=${TM_DB_PASS}
      - POSTGRES_DB=${TM_DB_NAME}
    volumes:
      - teslamate-db:/var/lib/postgresql/data
    networks:
      - proxynet
    ports:
      - 5432

  grafana:
    image: teslamate/grafana:latest
    environment:
      - DATABASE_USER=${TM_DB_USER}
      - DATABASE_PASS=${TM_DB_PASS}
      - DATABASE_NAME=${TM_DB_NAME}
      - DATABASE_HOST=database
      - GRAFANA_PASSWD=${GRAFANA_PW}
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PW}
      - GF_AUTH_BASIC_ENABLED=true
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_SERVER_ROOT_URL=https://${FQDN_GRAFANA}
    networks:
      - proxynet
    ports:
      - 3000
    volumes:
      - teslamate-grafana-data:/var/lib/grafana
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=${COMPOSE_PROJECT_NAME}_proxynet' # you need to change pd_ to something else if you use a different stack name when starting
      - 'traefik.port=3000'
      - 'traefik.backend=grafana'
      - 'traefik.backend.loadbalancer.method=drr'
      - 'traefik.frontend.rule=Host:${FQDN_GRAFANA}' # change this to your hostname. That hostname needs to point to your server
      - 'traefik.domain=${FQDN_GRAFANA}' # change this to your hostname. That hostname needs to point to your server

  mosquitto:
    image: eclipse-mosquitto:1.6
    networks:
      - proxynet
    ports:
      - 1883
      - 9001
    volumes:
      - mosquitto-conf:/mosquitto/config
      - mosquitto-data:/mosquitto/data

  proxy:
    image: traefik
    restart: always
    command:
      - '--loglevel=WARN'
      - '--api'
      # - "--entrypoints=Name:http Address::80"
      - '--entrypoints=Name:http Address::80 Redirect.EntryPoint:https'
      - '--entrypoints=Name:https Address::443 TLS'
      - '--defaultentrypoints=http,https'
      - '--acme'
      - '--acme.storage=/etc/acme/acme.json'
      - '--acme.entryPoint=https'
      - '--acme.onHostRule=true'
      - '--acme.httpChallenge'
      - '--acme.httpChallenge.entryPoint=http'
      - '--acme.email=${LETSENCRYPT_EMAIL}'
      ## comment out the next line to request a real certificate
      #- "--acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory" # uncomment this line if you want to test the lets encrypt certificate generation
      - '--docker'
      - '--docker.exposedByDefault=false'
      - '--docker.endpoint=unix:///var/run/docker.sock'
      - '--docker.watch'
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./.htpasswd:/auth/.htpasswd
      - ./acme/:/etc/acme/
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxynet
      - webgateway

volumes:
    teslamate-db:
    teslamate-grafana-data:
    mosquitto-conf:
    mosquitto-data:
```

_.env file_
```env
COMPOSE_PROJECT_NAME=tm

LETSENCRYPT_EMAIL=yourperson@lemail.com

TM_DB_USER=yourdbuser
TM_DB_PASS=yourdbpass
TM_DB_NAME=yourdbname
TM_TZ=Europe/Berlin

GRAFANA_USER=youruser
GRAFANA_PW=yoursupersecretpw

FQDN_GRAFANA=your.host.for.grafana.com
FQDN_TM=your.host.for.teslamate.com
```

**Comment by Helmi** [comment]
just edited the original post and added password protection for tesla mate to not have that exposed publicly.

**Comment by bahree** [comment]
This is awesome - thank you - something been wanting to do and will try it out and ping back!

**Comment by adriankumpf** [comment]
Awesome setup! Thank you very much for sharing. If you don't mind, I'd create an entry in the wiki with your _docker-compose.yml_?

**Comment by Helmi** [comment]
Sure, feel free to take and modify or whatever is needed.

**Comment by Helmi** [comment]
@adriankumpf I updated the compose file to allow PUT requests to the API to resume and suspend logging. Again widely untested. I get a 404 now instead of a 401 before but not sure if the 404 is due to the missing car (😥) or if something else isnt' working right but I think it should be the right approach.

Also removed some old stupid comments that I copied over from another file and that are not really needed here.

```
version: '3'

networks:
  proxynet:
    driver: bridge
  webgateway:
    external: true

services:
  teslamate:
    image: teslamate/teslamate:latest
    restart: unless-stopped
    depends_on:
      - database
    environment:
      - DATABASE_USER=${TM_DB_USER}
      - DATABASE_PASS=${TM_DB_PASS}
      - DATABASE_NAME=${TM_DB_NAME}
      - DATABASE_HOST=database
      - MQTT_HOST=mosquitto
      - VIRTUAL_HOST=${FQDN_TM}
      - TZ={$TM_TZ}
    networks:
      - proxynet  
    ports:
      - 4000
    cap_drop:
      - all
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=${COMPOSE_PROJECT_NAME}_proxynet'
      - 'traefik.port=4000'
      - 'traefik.backend=teslamate'
      - 'traefik.backend.loadbalancer.method=drr'
      - 'traefik.domain=${FQDN_TM}'
      - 'traefik.frontend.rule=Method:GET,POST,Host:${FQDN_TM}'
      - 'traefik.frontend.auth.basic.usersFile=/auth/.htpasswd'
      - 'traefik.frontendapi.rule=Method:PUT,Host:${FQDN_TM}'

  database:
    image: postgres:11
    environment:
      - POSTGRES_USER=${TM_DB_USER}
      - POSTGRES_PASSWORD=${TM_DB_PASS}
      - POSTGRES_DB=${TM_DB_NAME}
    volumes:
      - teslamate-db:/var/lib/postgresql/data
    networks:
      - proxynet
    ports:
      - 5432

  grafana:
    image: teslamate/grafana:latest
    environment:
      - DATABASE_USER=${TM_DB_USER}
      - DATABASE_PASS=${TM_DB_PASS}
      - DATABASE_NAME=${TM_DB_NAME}
      - DATABASE_HOST=database
      - GRAFANA_PASSWD=${GRAFANA_PW}
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PW}
      - GF_AUTH_BASIC_ENABLED=true
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_SERVER_ROOT_URL=https://${FQDN_GRAFANA}
    networks:
      - proxynet
    ports:
      - 3000
    volumes:
      - teslamate-grafana-data:/var/lib/grafana
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=${COMPOSE_PROJECT_NAME}_proxynet'
      - 'traefik.port=3000'
      - 'traefik.backend=grafana'
      - 'traefik.backend.loadbalancer.method=drr'
      - 'traefik.frontend.rule=Host:${FQDN_GRAFANA}'
      - 'traefik.domain=${FQDN_GRAFANA}'

  mosquitto:
    image: eclipse-mosquitto:1.6
    networks:
      - proxynet
    ports:
      - 1883
      - 9001
    volumes:
      - mosquitto-conf:/mosquitto/config
      - mosquitto-data:/mosquitto/data

  proxy:
    image: traefik
    restart: always
    command:
      - '--loglevel=WARN'
      - '--api'
      # - "--entrypoints=Name:http Address::80"
      - '--entrypoints=Name:http Address::80 Redirect.EntryPoint:https'
      - '--entrypoints=Name:https Address::443 TLS'
      - '--defaultentrypoints=http,https'
      - '--acme'
      - '--acme.storage=/etc/acme/acme.json'
      - '--acme.entryPoint=https'
      - '--acme.onHostRule=true'
      - '--acme.httpChallenge'
      - '--acme.httpChallenge.entryPoint=http'
      - '--acme.email=${LETSENCRYPT_EMAIL}'
      ## remove the comment for the following line to only send certificate requests to the sandbox service (for testing)
      #- "--acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory" # uncomment this line if you want to test the lets encrypt certificate generation
      - '--docker'
      - '--docker.exposedByDefault=false'
      - '--docker.endpoint=unix:///var/run/docker.sock'
      - '--docker.watch'
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./.htpasswd:/auth/.htpasswd
      - ./acme/:/etc/acme/
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxynet
      - webgateway

volumes:
    teslamate-db:
    teslamate-grafana-data:
    mosquitto-conf:
    mosquitto-data:
```

**Comment by adriankumpf** [comment]
Thanks, I'll update the wiki accordingly! The 404 indicates that it's indeed working correctly 👍

**Comment by Sebbo69** [comment]
What is the Tasker command for this Config?

**Comment by Helmi** [comment]
@Sebbo69 you just need to adjust the URL to the (sub)domain name you are using for the logger. Nothing special otherwise.

**Comment by Sebbo69** [comment]
your.host.for.grafana.com:4000/api/car/1/logging/resume has no funktion

**Comment by Sebbo69** [comment]
and with this config i dont have access to grafana. 
with this message:

[error] Could not check origin for Phoenix.Socket transport.

**Comment by DrMichael** [comment]
Can I use this on a host, where ports 80 and 443 are already in use otherwise?

**Comment by Helmi** [comment]
@Sebbo69 this setup is meant to run with FQDNs and you don't need a port. You need to set your subdomain name in the config and each (grafana and Teslamate) gets its own subdomain.

@DrMichael you can but you nede to modify the config accordingly. By default it's meant to run on 80 for the SSL retrieval and 443 for https.

**Comment by Sebbo69** [comment]
Yes I have 2 subdomains. One grafana. Xxxx.xx and other teslamate. Xxx. Xx

**Comment by Helmi** [comment]
ok, just remove the port from your URL then -  you don't need it anymore. If you followed the instructions you will need to enter the password but if you do a PUT request it won't need a password against the API.

**Comment by Sebbo69** [comment]
Problem is, with both sub it will come to teslamate setup site. Not to grafana.

**Comment by DrMichael** [comment]
@Helmi Ok, we have ports 80, 443, 3000, 4000 then open?
3000 for Grafana
4000 for Teslamate
80/443 for what?

**Comment by Helmi** [comment]
@DrMichael this setup uses SSL for all the web access. no 3000, no 4000. One subdomain for Grafana, one for  Teslamate. Everything on 443. Port 80 is used for the (automatic) SSL retrieval process. If you don't want to use 80/443 this is just not the right setup for you - use the default docker-compose file instead. This is more what you're looking for.

**Comment by Helmi** [comment]
@Sebbo69 are you sure your subdomains are configured the right way and you got your .env file right and in place? Be sure to check the log output of the proxy and check for error output on the console when you start it. If you setup your hostnames in the .env file and the subdomains are configured to point to your server it should work.

**Comment by Sebbo69** [comment]
Yes, at logfile are errors because the wrong Domain for the setup Page. Both sub.domains going in the same IP. I have double checked and complete New setup

**Comment by Helmi** [comment]
If you want send me your files by email and I can have a look at it - apart from that it's hard for me to help. 

github(at)helmilectric.com

**Comment by Sebbo69** [comment]
Okay, in 30 min.

**Comment by DrMichael** [comment]
> @DrMichael this setup uses SSL for all the web access. no 3000, no 4000. One subdomain for Grafana, one for Teslamate. Everything on 443. Port 80 is used for the (automatic) SSL retrieval process. If you don't want to use 80/443 this is just not the right setup for you - use the default docker-compose file instead. This is more what you're looking for.

Ah, ok...

**Comment by Helmi** [comment]
@adriankumpf the last docker-compose had a bug that would make grafana inaccessible. Thanks to @Sebbo69 I got aware of that and was able to fix it at least for my empty installation (still 8 days to go 🤤).

Here's the latest version. Maybe wait for confirmation from  @Sebbo69 later today before you put it on the wiki.

```
version: '3'

networks:
  proxynet:
    driver: bridge
  webgateway:
    external: true

services:
  teslamate:
    image: teslamate/teslamate:latest
    restart: unless-stopped
    depends_on:
      - database
    environment:
      - DATABASE_USER=${TM_DB_USER}
      - DATABASE_PASS=${TM_DB_PASS}
      - DATABASE_NAME=${TM_DB_NAME}
      - DATABASE_HOST=database
      - MQTT_HOST=mosquitto
      - VIRTUAL_HOST=${FQDN_TM}
      - TZ={$TM_TZ}
    networks:
      - proxynet  
    ports:
      - 4000
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=${COMPOSE_PROJECT_NAME}_proxynet'
      - 'traefik.port=4000'
      - 'traefik.backend=teslamate'
      - 'traefik.backend.loadbalancer.method=drr'
      - 'traefik.domain=${FQDN_TM}'
      - 'traefik.tm.frontend.rule=Method:GET,POST;Host:${FQDN_TM}'
      - 'traefik.tm.frontend.auth.basic.usersFile=/auth/.htpasswd'
      - 'traefik.tmapi.frontend.rule=Method:PUT;Host:${FQDN_TM}'
  database:
    image: postgres:11
    environment:
      - POSTGRES_USER=${TM_DB_USER}
      - POSTGRES_PASSWORD=${TM_DB_PASS}
      - POSTGRES_DB=${TM_DB_NAME}
    volumes:
      - teslamate-db:/var/lib/postgresql/data
    networks:
      - proxynet
    ports:
      - 5432

  grafana:
    image: teslamate/grafana:latest
    environment:
      - DATABASE_USER=${TM_DB_USER}
      - DATABASE_PASS=${TM_DB_PASS}
      - DATABASE_NAME=${TM_DB_NAME}
      - DATABASE_HOST=database
      - GRAFANA_PASSWD=${GRAFANA_PW}
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PW}
      - GF_AUTH_BASIC_ENABLED=true
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_SERVER_ROOT_URL=https://${FQDN_GRAFANA}
    networks:
      - proxynet
    ports:
      - 3000
    volumes:
      - teslamate-grafana-data:/var/lib/grafana
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=${COMPOSE_PROJECT_NAME}_proxynet'
      - 'traefik.port=3000'
      - 'traefik.backend=grafana'
      - 'traefik.backend.loadbalancer.method=drr'
      - 'traefik.frontend.rule=Host:${FQDN_GRAFANA}'
      - 'traefik.domain=${FQDN_GRAFANA}'

  mosquitto:
    image: eclipse-mosquitto:1.6
    networks:
      - proxynet
    ports:
      - 1883
      - 9001
    volumes:
      - mosquitto-conf:/mosquitto/config
      - mosquitto-data:/mosquitto/data

  proxy:
    image: traefik
    restart: always
    command:
      - '--loglevel=WARN'
      - '--entrypoints=Name:http Address::80 Redirect.EntryPoint:https'
      - '--entrypoints=Name:https Address::443 TLS'
      - '--defaultentrypoints=http,https'
      - '--acme'
      - '--acme.storage=/etc/acme/acme.json'
      - '--acme.entryPoint=https'
      - '--acme.onHostRule=true'
      - '--acme.httpChallenge'
      - '--acme.httpChallenge.entryPoint=http'
      - '--acme.email=${LETSENCRYPT_EMAIL}'
      ## remove the comment for the following line to only send certificate requests to the sandbox service (for testing)
      #- "--acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory" # uncomment this line if you want to test the lets encrypt certificate generation
      - '--docker'
      - '--docker.exposedByDefault=false'
      - '--docker.endpoint=unix:///var/run/docker.sock'
      - '--docker.watch'
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./.htpasswd:/auth/.htpasswd
      - ./acme/:/etc/acme/
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxynet
      - webgateway

volumes:
    teslamate-db:
    teslamate-grafana-data:
    mosquitto-conf:
    mosquitto-data:
```

**Comment by adriankumpf** [comment]
Thanks @Helmi!

I tried to set it up myself and noticed that v2 of traefik will be released shortly. It has a lot of breaking changes and configuring e.g. HTTP redirects is more verbose but overall it makes a things easier. That's the config I came up with:

```YAML
version: '3'

services:
  teslamate:
    image: teslamate/teslamate:latest
    restart: unless-stopped
    depends_on:
      - database
    environment:
      - DATABASE_USER=${TM_DB_USER}
      - DATABASE_PASS=${TM_DB_PASS}
      - DATABASE_NAME=${TM_DB_NAME}
      - DATABASE_HOST=database
      - MQTT_HOST=mosquitto
      - VIRTUAL_HOST=${FQDN_TM}
      - TZ={$TM_TZ}
    labels:
      - 'traefik.enable=true'
      - 'traefik.port=4000'
      - "traefik.http.middlewares.redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.auth.basicauth.usersfile=/auth/.htpasswd"
      - "traefik.http.routers.teslamate-insecure.rule=Host(`${FQDN_TM}`)"
      - "traefik.http.routers.teslamate-insecure.middlewares=redirect"
      - "traefik.http.routers.teslamate.rule=Host(`${FQDN_TM}`)"
      - "traefik.http.routers.teslamate.middlewares=auth"
      - "traefik.http.routers.teslamate.entrypoints=websecure"
      - "traefik.http.routers.teslamate.tls.certresolver=tmhttpchallenge"

  database:
    image: postgres:11
    environment:
      - POSTGRES_USER=${TM_DB_USER}
      - POSTGRES_PASSWORD=${TM_DB_PASS}
      - POSTGRES_DB=${TM_DB_NAME}
    volumes:
      - teslamate-db:/var/lib/postgresql/data

  grafana:
    image: teslamate/grafana:latest
    environment:
      - DATABASE_USER=${TM_DB_USER}
      - DATABASE_PASS=${TM_DB_PASS}
      - DATABASE_NAME=${TM_DB_NAME}
      - DATABASE_HOST=database
      - GRAFANA_PASSWD=${GRAFANA_PW}
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PW}
      - GF_AUTH_BASIC_ENABLED=true
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_SERVER_ROOT_URL=https://${FQDN_GRAFANA}
    volumes:
      - teslamate-grafana-data:/var/lib/grafana
    labels:
      - 'traefik.enable=true'
      - 'traefik.port=3000'
      - "traefik.http.middlewares.redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.grafana-insecure.rule=Host(`${FQDN_GRAFANA}`)"
      - "traefik.http.routers.grafana-insecure.middlewares=redirect"
      - "traefik.http.routers.grafana.rule=Host(`${FQDN_GRAFANA}`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls.certresolver=tmhttpchallenge"

  mosquitto:
    image: eclipse-mosquitto:1.6
    volumes:
      - mosquitto-conf:/mosquitto/config
      - mosquitto-data:/mosquitto/data

  proxy:
    image: traefik:v2.0
    command:
      - "--global.sendAnonymousUsage=false"
      - "--providers.docker"
      - "--providers.docker.exposedByDefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.tmhttpchallenge.acme.httpchallenge=true"
      - "--certificatesresolvers.tmhttpchallenge.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.tmhttpchallenge.acme.email=${LETSENCRYPT_EMAIL}"
      - "--certificatesresolvers.tmhttpchallenge.acme.storage=/etc/acme/acme.json"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./.htpasswd:/auth/.htpasswd
      - ./acme/:/etc/acme/
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
    teslamate-db:
    teslamate-grafana-data:
    mosquitto-conf:
    mosquitto-data:
```
