### ISSUE TITLE
Contributing / Local testing setup ?

### ISSUE THREAD

**Issue by normalfaults** [adriankumpf/teslamate#158]
I am new to elixir however I want to help contribute. I spent some time last weekend setting up teslamate for local development. In the process I was looking at your build scripts and other components however I couldn't get the testing and build flow working properly. Would you mind sharing how you setup teslamate for development in your environment and any tips on how to best shape pull requests?

**Comment by adriankumpf** [comment]
> I am new to elixir however I want to help contribute.

Awesome!

I should write documentation on how to get started. That's what I have so far:

### Initial setup

Start postgres and mosquitto locally. Then download all dependencies and setup the database:

```bash
# download dependencies
mix deps.get

# create database and run migrations
mix ecto.setup

# download JavaScript dependencies
npm install --prefix ./assets

# an alias for all of the above commands which uses yarn instead of npm:
mix setup
```

### Development

#### TeslaMate

Start an iex session in another terminal window:

```bash
iex -S mix phx.server
```

Usually I sign in with my real Tesla account. Sometimes it makes sense to use a fresh test account.

##### Compiling

```bash
mix compile
```

##### Hot reloading

To immediately apply your local changes changes open or reload `http://localhost:4000`. You can also reload specific modules via iex, for example:

```elixir
iex> r TeslaMate.Vehicles.Vehicle
```

##### Code formatting

```bash
mix format
```

#### Grafana

I usually run Grafana with a custom docker-compose file:

_docker-compose.yml_

```YAML
version: '3'
services:
  grafana:
    image: teslamate-grafana:latest
    environment:
      - DATABASE_USER=postgres
      - DATABASE_PASS=postgres
      - DATABASE_NAME=teslamate_dev
      - DATABASE_HOST=host.docker.internal
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
    grafana-data:
```

```bash
# build the image
make grafana

# run the container
docker-compose up grafana
```

To change a dashboard edit it locally and save it as a json file at `./grafana/dashboards/`.

### Running tests

```bash
# initially create the test database
MIX_ENV=test mix ecto.setup

# run tests
mix test
```
