### ISSUE TITLE
Multiple dashboards broke

### ISSUE THREAD

**Issue by cwanja** [adriankumpf/teslamate#271]
**Describe the bug**
Loading the Drives dashboard produces an error

**To Reproduce**
1. Open Grafana
2. Click Drive dashboard
3. Error (see screenshot) 

**Expected behavior**
Table of drives

**Screenshots**
![Screen Shot 2019-11-25 at 4 52 50 PM](https://user-images.githubusercontent.com/54645561/69585021-2fd89e00-0fa4-11ea-9cce-ac2bc44e4b56.png)

**Operating environment (please complete the following information):**
 - OS: [Raspbian]
 - Version [V1.13]

**Comment by cwanja** [comment]
Seems to carry over to the Efficiency dashboard as well.

**Comment by adriankumpf** [comment]
That's weird. These dashboards haven't changed with the latest update. It could be an issue with Grafana.

* Do you run the docker images or did you install manually? If the latter is the case, what's your Grafana version?
* Does it work with other browsers?

**Comment by cwanja** [comment]
Docker images. It was working prior to the update. For what it is worth, here is the version Grafana v6.5.0 (24a5d2f).

Tried in Safari (desktop and mobile) and Chrome (mobile) - neither work. Same error.

**Comment by adriankumpf** [comment]
I uploaded an alternative docker image that is based on an older version of Grafana. Could you temporarily change the docker-compose file to see if it works?

You'd have to change the following line:

```yaml
  # ... 

  grafana:
    image: teslamate/grafana:latest

  # ... 
```

to 


```yaml
  # ... 

  grafana:
    image: teslamate/grafana:1.13.0-6.3

  # ... 
```
