### ISSUE TITLE
Drives not getting logged

### ISSUE THREAD

**Issue by natrlhy** [adriankumpf/teslamate#2745]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I moved to the `:edge` release a few weeks back. I'm not seeing drives get logged

### Expected Behavior

Current Drives should show up in the Drives Grafana Dashboard

### Steps To Reproduce

1. Click on Drives
2. Observe recent drive
3. Drives not showing up

### Relevant log output

```shell
root@teslamate:~/docker# docker-compose logs teslamate | grep car_id=1
teslamate_1  | 2022-07-12 22:21:37.305 car_id=1 [info] Start / :asleep
teslamate_1  | 2022-07-13 08:18:33.672 car_id=1 [info] Start / :online
teslamate_1  | 2022-07-13 08:18:34.016 car_id=1 [info] Connecting ...
teslamate_1  | 2022-07-13 08:18:49.582 car_id=1 [info] Driving / Start
teslamate_1  | 2022-07-13 09:04:24.810 car_id=1 [info] Start / :online
teslamate_1  | 2022-07-13 09:04:25.044 car_id=1 [info] Connecting ...
teslamate_1  | 2022-07-13 09:06:36.966 car_id=1 [info] Start / :asleep
teslamate_1  | 2022-07-13 09:06:37.021 car_id=1 [info] Disconnecting ...
teslamate_1  | 2022-07-13 09:12:48.914 car_id=1 [info] Start / :online
teslamate_1  | 2022-07-13 09:12:48.979 car_id=1 [info] Connecting ...
teslamate_1  | 2022-07-13 09:12:49.392 car_id=1 [info] Charging / SOC: 18% / Work
teslamate_1  | 2022-07-13 09:12:49.393 car_id=1 [info] Disconnecting ...
```

### Additional data

[drives.csv](https://github.com/adriankumpf/teslamate/files/9104851/drives.csv)
[positions.csv](https://github.com/adriankumpf/teslamate/files/9104852/positions.csv)

### Type of installation

Docker

### Version

1.27.0-dev

**Comment by natrlhy** [comment]
Moved from edge to latest and still no past or recent drives. I can see the map always knows where the car is when driving

**Comment by natrlhy** [comment]
Some history to what I've done in the past month:

Changed to `:edge` branch
upgraded to postgres 14 (followed steps [here](https://docs.teslamate.org/docs/maintenance/upgrading_postgres)
changed grafana to `:edge`

Could ANY of this case this issue where drives aren't logged?
What should I be looking for in the respective containers?

**Comment by natrlhy** [comment]
In case here's my yml file:

```
version: '3'
services:
  teslamate:
    image: teslamate/teslamate:latest
    restart: always
    environment:
      - ENCRYPTION_KEY=long key here with upper/lower case letters and numbers (no special chars as it seemed like it didn't like that)
      - DATABASE_USER=teslamate
      - DATABASE_PASS=passhere
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=db
      - MQTT_HOST=mosquitto
      - TZ=America/Los_Angeles       # (optional) replace to use local time in debug logs. See "Configuration".
      - VIRTUAL_HOST=10.10.10.8 # if you're going to access the UI from another  machine replace
                               # "localhost" with the hostname / IP address of the docker host.
    ports:
      - 4000:4000
    cap_drop:
      - all

  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=teslamate
      - POSTGRES_PASSWORD=passhere
      - POSTGRES_DB=teslamate
    volumes:
      - teslamate-db:/var/lib/postgresql/data

  grafana:
    image: teslamate/grafana:latest
    restart: always
    environment:
      - DATABASE_USER=teslamate
      - DATABASE_PASS=passhere
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=db
    ports:
      - 3000:3000
    volumes:
      - teslamate-grafana-data:/var/lib/grafana

  mosquitto:
    image: eclipse-mosquitto:2
    restart: always
    ports:
      - 1883:1883
    volumes:
      - mosquitto-conf:/mosquitto/config
      - mosquitto-data:/mosquitto/data

volumes:
    teslamate-db:
    teslamate-grafana-data:
    mosquitto-conf:
    mosquitto-data:
    ```
