### ISSUE TITLE
After update to 1.27.2 I get this "db query error: pq: password authentication failed for user "admin""

### ISSUE THREAD

**Issue by JonMurphy** [adriankumpf/teslamate#3119]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

After updating from 1.27.1 to 1.27.2 I can not longer access the data.  I get this error on the Grafana WebGUI. 
```
db query error: pq: password authentication failed for user "admin"
```
All has worked well over the past few months.  This feels like something changed with the database password code (maybe over the past year) that I did not figure out.  

### Expected Behavior

expect to be able to see the data on all Grafana WebGUIs

### Steps To Reproduce

1. go to `http://teslamate.localdomain:4000`
2. click on any one of **Dashboards**
3. See error on all Grafana pages

### Relevant log output

```shell
pi@teslamate:~/teslamate $ docker-compose logs
Attaching to teslamate_teslamate_1, teslamate_grafana_1, teslamate_database_1, teslamate_mosquitto_1

. . .

database_1   | 2023-02-09 23:23:33.691 UTC [1] LOG:  received fast shutdown request
database_1   | 2023-02-09 23:23:34.466 UTC [1] LOG:  aborting any active transactions
database_1   | 2023-02-09 23:23:34.467 UTC [509] FATAL:  terminating connection due to administrator command
database_1   | 2023-02-09 23:23:34.467 UTC [513] FATAL:  terminating connection due to administrator command
database_1   | 2023-02-09 23:23:34.473 UTC [507] FATAL:  terminating connection due to administrator command
database_1   | 2023-02-09 23:23:34.477 UTC [514] FATAL:  terminating connection due to administrator command
database_1   | 2023-02-09 23:23:34.477 UTC [506] FATAL:  terminating connection due to administrator command
database_1   | 2023-02-09 23:23:34.479 UTC [511] FATAL:  terminating connection due to administrator command
database_1   | 2023-02-09 23:23:34.482 UTC [510] FATAL:  terminating connection due to administrator command
database_1   | 2023-02-09 23:23:34.494 UTC [512] FATAL:  terminating connection due to administrator command
database_1   | 2023-02-09 23:23:34.495 UTC [505] FATAL:  terminating connection due to administrator command
database_1   | 2023-02-09 23:23:34.525 UTC [1] LOG:  background worker "logical replication launcher" (PID 34) exited with exit code 1
database_1   | 2023-02-09 23:23:34.541 UTC [508] FATAL:  terminating connection due to administrator command
database_1   | 2023-02-09 23:23:34.559 UTC [29] LOG:  shutting down
database_1   | 2023-02-09 23:23:34.696 UTC [1] LOG:  database system is shut down
database_1   | 
database_1   | PostgreSQL Database directory appears to contain a database; Skipping initialization
database_1   | 
database_1   | 2023-02-09 23:24:41.935 UTC [1] LOG:  starting PostgreSQL 12.13 (Debian 12.13-1.pgdg110+1) on arm-unknown-linux-gnueabihf, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 32-bit
database_1   | 2023-02-09 23:24:41.937 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
database_1   | 2023-02-09 23:24:41.937 UTC [1] LOG:  listening on IPv6 address "::", port 5432
database_1   | 2023-02-09 23:24:41.957 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
database_1   | 2023-02-09 23:24:42.030 UTC [27] LOG:  database system was shut down at 2023-02-09 23:23:34 UTC
database_1   | 2023-02-09 23:24:42.063 UTC [1] LOG:  database system is ready to accept connections
database_1   | 2023-02-09 23:26:30.379 UTC [50] FATAL:  password authentication failed for user "admin"
database_1   | 2023-02-09 23:26:30.379 UTC [50] DETAIL:  Role "admin" does not exist.
database_1   | 	Connection matched pg_hba.conf line 99: "host all all all md5"
database_1   | 2023-02-09 23:26:30.386 UTC [52] FATAL:  password authentication failed for user "admin"
database_1   | 2023-02-09 23:26:30.386 UTC [52] DETAIL:  Role "admin" does not exist.
database_1   | 	Connection matched pg_hba.conf line 99: "host all all all md5"
database_1   | 2023-02-09 23:26:30.386 UTC [51] FATAL:  password authentication failed for user "admin"
database_1   | 2023-02-09 23:26:30.386 UTC [51] DETAIL:  Role "admin" does not exist.
database_1   | 	Connection matched pg_hba.conf line 99: "host all all all md5"
database_1   | 2023-02-09 23:26:30.706 UTC [53] FATAL:  password authentication failed for user "admin"
database_1   | 2023-02-09 23:26:30.706 UTC [53] DETAIL:  Role "admin" does not exist.
database_1   | 	Connection matched pg_hba.conf line 99: "host all all all md5"
database_1   | 2023-02-09 23:26:30.730 UTC [54] FATAL:  password authentication failed for user "admin"
database_1   | 2023-02-09 23:26:30.730 UTC [54] DETAIL:  Role "admin" does not exist.
database_1   | 	Connection matched pg_hba.conf line 99: "host all all all md5"
database_1   | 2023-02-09 23:26:30.774 UTC [56] FATAL:  password authentication failed for user "admin"
database_1   | 2023-02-09 23:26:30.774 UTC [56] DETAIL:  Role "admin" does not exist.
database_1   | 	Connection matched pg_hba.conf line 99: "host all all all md5"
database_1   | 2023-02-09 23:26:30.774 UTC [55] FATAL:  password authentication failed for user "admin"
database_1   | 2023-02-09 23:26:30.774 UTC [55] DETAIL:  Role "admin" does not exist.
database_1   | 	Connection matched pg_hba.conf line 99: "host all all all md5"
database_1   | 2023-02-09 23:26:30.800 UTC [57] FATAL:  password authentication failed for user "admin"
database_1   | 2023-02-09 23:26:30.800 UTC [57] DETAIL:  Role "admin" does not exist.
database_1   | 	Connection matched pg_hba.conf line 99: "host all all all md5"
database_1   | 2023-02-09 23:26:30.866 UTC [58] FATAL:  password authentication failed for user "admin"
database_1   | 2023-02-09 23:26:30.866 UTC [58] DETAIL:  Role "admin" does not exist.
database_1   | 	Connection matched pg_hba.conf line 99: "host all all all md5"
database_1   | 2023-02-09 23:26:30.874 UTC [59] FATAL:  password authentication failed for user "admin"
database_1   | 2023-02-09 23:26:30.874 UTC [59] DETAIL:  Role "admin" does not exist.
database_1   | 	Connection matched pg_hba.conf line 99: "host all all all md5"
database_1   | 2023-02-09 23:26:30.921 UTC [60] FATAL:  password authentication failed for user "admin"
database_1   | 2023-02-09 23:26:30.921 UTC [60] DETAIL:  Role "admin" does not exist.
database_1   | 	Connection matched pg_hba.conf line 99: "host all all all md5"
database_1   | 2023-02-09 23:26:30.935 UTC [61] FATAL:  password authentication failed for user "admin"
database_1   | 2023-02-09 23:26:30.935 UTC [61] DETAIL:  Role "admin" does not exist.
database_1   | 	Connection matched pg_hba.conf line 99: "host all all all md5"
database_1   | 2023-02-09 23:26:30.961 UTC [62] FATAL:  password authentication failed for user "admin"
database_1   | 2023-02-09 23:26:30.961 UTC [62] DETAIL:  Role "admin" does not exist.
database_1   | 	Connection matched pg_hba.conf line 99: "host all all all md5"
database_1   | 2023-02-09 23:26:30.989 UTC [63] FATAL:  password authentication failed for user "admin"
database_1   | 2023-02-09 23:26:30.989 UTC [63] DETAIL:  Role "admin" does not exist.
database_1   | 	Connection matched pg_hba.conf line 99: "host all all all md5"
pi@teslamate:~/teslamate $
```

### Screenshots

<img width="1064" alt="Screen Shot 2023-02-10 at 1 42 01 PM" src="https://user-images.githubusercontent.com/15616372/218183323-c2cb8512-7076-47b7-8c39-d2573a3a4235.png">

### Additional data

```
pi@teslamate:~ $ cat /proc/device-tree/model;echo
Raspberry Pi 3 Model B Plus Rev 1.3

pi@teslamate:~ $ lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye
```

```
pi@teslamate:~ $ cat ~/teslamate/docker-compose.yml
version: "3"

services:
  teslamate:
    image: teslamate/teslamate:latest
    restart: always
    environment:
      - ENCRYPTION_KEY=RandomCraracters2
      - DATABASE_USER=teslamate
      - DATABASE_PASS=mySecret
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
      - MQTT_HOST=mosquitto
    ports:
      - 4000:4000
    volumes:
      - ./import:/opt/app/import
    cap_drop:
      - all

  database:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_USER=teslamate
      - POSTGRES_PASSWORD=mySecret
      - POSTGRES_DB=teslamate
    volumes:
      - teslamate-db:/var/lib/postgresql/data

  grafana:
    image: teslamate/grafana:latest
    restart: always
    environment:
      - DATABASE_USER=admin
      - DATABASE_PASS=RandomCraracters
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
    ports:
      - 3000:3000
    volumes:
      - teslamate-grafana-data:/var/lib/grafana

  mosquitto:
    image: eclipse-mosquitto:2
    restart: always
    command: mosquitto -c /mosquitto-no-auth.conf
    # ports:
    #   - 1883:1883
    volumes:
      - mosquitto-conf:/mosquitto/config
      - mosquitto-data:/mosquitto/data

volumes:
  teslamate-db:
  teslamate-grafana-data:
  mosquitto-conf:
  mosquitto-data:

pi@teslamate:~ $ 
```

This device is local only and has **no** access from the internet to the RPi.

### Type of installation

Docker

### Version

1.27.2

**Comment by JonMurphy** [comment]
Best I can tell the POSTGRES_USER changed on the postgres DB side during the update to 1.27.2.  The user is **not** `admin`.  It should be `teslamate`.


I did this to check:
```
pi@teslamate:~/teslamate $ docker exec -it b8da6abdce97 bash
root@b8da6abdce97:/#

root@b8da6abdce97:/# psql -U teslamate
psql (12.13 (Debian 12.13-1.pgdg110+1))
Type "help" for help.

teslamate=# \du
                                   List of roles
 Role name |                         Attributes                         | Member of 
-----------+------------------------------------------------------------+-----------
 teslamate | Superuser, Create role, Create DB, Replication, Bypass RLS | {}

teslamate=# \dt
                List of relations
 Schema |        Name        | Type  |   Owner   
--------+--------------------+-------+-----------
 public | addresses          | table | teslamate
 public | car_settings       | table | teslamate
 public | cars               | table | teslamate
 public | charges            | table | teslamate
 public | charging_processes | table | teslamate
 public | drives             | table | teslamate
 public | geofences          | table | teslamate
 public | positions          | table | teslamate
 public | schema_migrations  | table | teslamate
 public | settings           | table | teslamate
 public | states             | table | teslamate
 public | tokens             | table | teslamate
 public | updates            | table | teslamate
(13 rows)

teslamate=# 
```

But I have no clue how to change this on the Teslamate side.  Currently my `docker-compose.yml` file states this:
```
pi@teslamate:~ $ cat ~/teslamate/docker-compose.yml
version: "3"

services:
  teslamate:
. . .
  database:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_USER=teslamate
      - POSTGRES_PASSWORD=mySecret
      - POSTGRES_DB=teslamate
    volumes:
      - teslamate-db:/var/lib/postgresql/data

  grafana:
    image: teslamate/grafana:latest
    restart: always
. . .
```
So how to a tell Teslamate to have the user be `teslamate` and not `admin`.

**Comment by vgutta** [comment]
I'm having the same issue but haven't seen anyone post about this so I'm wondering if this is an issue limited to arm64

**Comment by JonMurphy** [comment]
> how to a tell Teslamate to have the user be teslamate and not admin

bump?!?

**Comment by AbnerHuang2** [comment]
> I was having a similar issue then reinstalled the OS after trying a bunch of things and it works properly now
what's did you do?

**Comment by dyxyl** [comment]
@JonMurphy The problem is on the grafana side.  In your `docker-compose.yml` you have

```
  grafana:
    image: teslamate/grafana:latest
    restart: always
    environment:
      - DATABASE_USER=admin
      - DATABASE_PASS=RandomCraracters
      ...
```
but it should be
```
      - DATABASE_USER=teslamate
      - DATABASE_PASS=mySecret
```

**Comment by JonMurphy** [comment]
that did not work.  Now I am locked out of Grafana.

<img width="500" alt="Screen Shot 2023-07-19 at 10 37 00 AM" src="https://github.com/adriankumpf/teslamate/assets/15616372/3beda1e6-5a70-4991-9d95-22aea6b86708">

**Comment by JonMurphy** [comment]
Since passwords and TeslaMate and I are not getting along - how do I remove all of the passwords and set things so passwords are not requested or needed?
And if I cannot get rid of them all, how do I get rid of the ones related to Grafana?

The RPi device with TeslaMate is behind a firewall and is NOT accessed via the Internet.  It is only used on my local, in house, network.

**Comment by dyxyl** [comment]
The `DATABASE_USER` and `DATABASE_PASS` in the `docker-compose.yml` are used by grafana to connect to the teslamate PostgreSQL database and nothing else.

The user for the grafana dashboard login should be `admin` with the password you set for it previously as described in step 3 of https://docs.teslamate.org/docs/installation/docker#usage.

**Comment by JonMurphy** [comment]
More importantly (for the moment) [I cannot access the Grafana graphs](https://github.com/adriankumpf/teslamate/issues/3119#issuecomment-1642321513).  

How do a reset the password?

Is there a section in the `docker-compose.yml` config file for this?

The ID is one of two things: either `teslamate` or `admin`.  Sadly I've changed passwords way too many times trying to get things to work....

---

> The DATABASE_USER and DATABASE_PASS in the docker-compose.yml are used by grafana to connect to the teslamate PostgreSQL database and nothing else.

My head just popped!  I've always thought of this as my access to get to the Grafana graphs.  So let me state this a little different to make sure I understand.  In this section...
```
grafana:
    image: teslamate/grafana:latest
    restart: always
    environment:
      - DATABASE_USER=teslamate
      - DATABASE_PASS= #insert your secure database password!
```

... is a client access for Grafana to be able to read data from the teslamate PostgreSQL database (and nothing else)??
