### ISSUE TITLE
unsupported external secret

### ISSUE THREAD

**Issue by mfscorp** [adriankumpf/teslamate#3133]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Upon starting stack in portainer it fails with error:
`failed to deploy a stack: Network teslamate_default Creating Network teslamate_default Created Container teslamate-teslamate-1 Creating Container teslamate-grafana-1 Creating Container teslamate-mosquitto-1 Creating Container teslamate-database-1 Creating unsupported external secret teslamate-encryption`

### Expected Behavior

expect that it can read out the secrets from portainer and starts up the container with secrets setup

### Steps To Reproduce

1. setup secrets in portainer (swarm)
![2023-02-25_18h47_19](https://user-images.githubusercontent.com/34352826/221371799-71173b20-293a-4d81-9db0-021dc1835ef9.jpg)

2. setup stack with:
```
secrets:
  teslamate-encryption:
    external: true

services:
  teslamate:
    image: teslamate/teslamate:latest
    restart: always
    environment:
      - ENCRYPTION_KEY=/run/secrets/teslamate-encryption
      - DATABASE_USER=teslamate
      - DATABASE_PASS=thatsasecret
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
      - MQTT_HOST=mosquitto
    ports:
      - 4000:4000
    volumes:
      - /path/in/host/import:/opt/app/import
    cap_drop:
      - all
    secrets:
      - teslamate-encryption

  database:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=teslamate
      - POSTGRES_PASSWORD=thisisanothersecret
      - POSTGRES_DB=teslamate
    volumes:
      - /path/in/host/database:/var/lib/postgresql/data

  grafana:
    image: teslamate/grafana:latest
    restart: always
    environment:
      - DATABASE_USER=teslamate
      - DATABASE_PASS=thatsasecret
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
    ports:
      - 3000:3000
    volumes:
      - /path/in/host/grafana:/var/lib/grafana

  mosquitto:
    image: eclipse-mosquitto:2
    restart: always
    command: mosquitto -c /mosquitto-no-auth.conf
    # ports:
    #   - 1883:1883
    volumes:
      - /path/in/host/mosquitto-conf:/mosquitto/config
      - /path/in/host/mosquitto-data:/mosquitto/data
```
3. start stack

### Relevant log output

```shell
container does not start and gives error on startup:
`failed to deploy a stack: Network teslamate_default Creating Network teslamate_default Created Container teslamate-teslamate-1 Creating Container teslamate-grafana-1 Creating Container teslamate-mosquitto-1 Creating Container teslamate-database-1 Creating unsupported external secret teslamate-encryption`
```

### Type of installation

Docker

### Version

v.1.27.2
