### ISSUE TITLE
I can't start teslamate UI

### ISSUE THREAD

**Issue by chris777c** [adriankumpf/teslamate#3345]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hello,

I can't start webUI teslamate on http://ip:4000 but grafana UI work.

### Expected Behavior

 docker ps

CONTAINER ID   IMAGE                        COMMAND                  CREATED         STATUS         PORTS                                       NAMES

5836382bacf0   teslamate/grafana:latest     "/run.sh"                7 minutes ago   Up 7 minutes   0.0.0.0:3000->3000/tcp, :::3000->3000/tcp   home-grafana-1

158a64383a8c   postgres:15                  "docker-entrypoint.s…"   7 minutes ago   Up 7 minutes   5432/tcp                                    home-database-1

eb6cf0b7efa9   eclipse-mosquitto:2          "/docker-entrypoint.…"   7 minutes ago   Up 7 minutes   1883/tcp                                    home-mosquitto-1

9bdfcb75da2f   teslamate/teslamate:latest   "tini -- /bin/sh /en…"   7 minutes ago   Up 7 minutes   0.0.0.0:4000->4000/tcp, :::4000->4000/tcp   home-teslamate-1

### Steps To Reproduce

1 - create docker compose
nano docker-compose.yml
2 - docker compose up -d

### Relevant log output

```shell
docker logs -f home-database-1

PostgreSQL Database directory appears to contain a database; Skipping initialization
2023-09-16 05:59:36.900 UTC [1] LOG:  starting PostgreSQL 15.4 (Debian 15.4-2.pgdg120+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
2023-09-16 05:59:36.901 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2023-09-16 05:59:36.901 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2023-09-16 05:59:36.907 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2023-09-16 05:59:36.923 UTC [28] LOG:  database system was shut down at 2023-09-16 05:59:30 UTC
2023-09-16 05:59:36.942 UTC [1] LOG:  database system is ready to accept connections

docker logs -f home-teslamate-1

waiting for postgres at database:5432
waiting for postgres at database:5432
waiting for postgres at database:5432
waiting for postgres at database:5432
```

### Screenshots

-

### Additional data

-

### Type of installation

Docker

### Version

last version

**Comment by webserviceXXL** [comment]
Did you check your firewall? Maybe the configuration allows port 3000 (grafan) but not the port 4000?

**Comment by chris777c** [comment]
Hello,

Thank you for reply, but no have activated firewall on my Odroid C2.

**Comment by 0x09AF** [comment]
I have the same issue. Running stack in docker but without the database. I can access Grafana but the main UI is not loading. I do use an external database. All firewall ports are allowed and confirmed by `ss -tlnp`.  
This is what shows in docker logs:
```
teslamate    | waiting for postgres at 10.3.3.5:5432
```

Although `docker ps` shows that the container is running and port open on `0.0.0.0:4000`
```
docker-ext:~/teslamate$ curl localhost:4000
curl: (56) Recv failure: Connection reset by peer
docker-ext:~/teslamate$ curl localhost:3000
<a href="/login">Found</a>.
```

**Comment by 0x09AF** [comment]
I had a problem with exact same symptoms. Make sure your dockers can talk to each other (on the same network
). Run ping command from inside the teslamate container to make sure it can see the DB. I use an external database and had to change some defaults in `/etc/postgres/16/main/postgresql.conf` and `/etc/postgres/16/main/pg_hba.conf`

**Comment by chris777c** [comment]
thank you for reply, but no have ping command on pod teslamate, you know su password for exec apt install ping ?

**Comment by 0x09AF** [comment]
Make sure they're on the same (docker) network and make sure you're pointing to the right host. In the docker network it is usually the container name.
What do you have in the `DATABASE_HOST` variable? Either set it to `158a64383a8c` or `home-database-1`

**Comment by chris777c** [comment]
I try to change `DATABASE_HOST` variable to `home-database-1` in file docker compose, same behavior.

```
docker logs -f home-teslamate-1

waiting for postgres at home-database-1:5432
waiting for postgres at home-database-1:5432
waiting for postgres at home-database-1:5432
waiting for postgres at home-database-1:5432
```

**Comment by 0x09AF** [comment]
Check your `docker-compose.yml` for typos (or show it here) and inspect the stack network: `docker network inspect <teslamate_network_1>`

**Comment by chris777c** [comment]
Here my docker-compose.yml:

```
version: "3"

services:
  teslamate:
    image: teslamate/teslamate:latest
    restart: always
    environment:
      - ENCRYPTION_KEY=&MuDc9z6V7B9BHRdpG6&w%mjAPM
      - DATABASE_USER=teslamate
      - DATABASE_PASS=secret
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=home-database-1
      - MQTT_HOST=mosquitto
    ports:
      - 4000:4000
    volumes:
      - ./import:/opt/app/import
    cap_drop:
      - all

  database:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=teslamate
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=teslamate
    volumes:
      - teslamate-db:/var/lib/postgresql/data

  grafana:
    image: teslamate/grafana:latest
    restart: always
    environment:
      - DATABASE_USER=teslamate
      - DATABASE_PASS=secret
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
    ports:
      - 3000:3000
    volumes:
      - teslamate-grafana-data:/var/lib/grafana

  mosquitto:
    image: eclipse-mosquitto:2
    restart: always
    command: mosquitto -c /mosquitto-no-auth.conf
    # ports:
    #   - 1883:1883
    volumes:
      - mosquitto-conf:/mosquitto/config
      - mosquitto-data:/mosquitto/data

volumes:
  teslamate-db:
  teslamate-grafana-data:
  mosquitto-conf:
  mosquitto-data:
```

and 


```
docker network inspect home_default

[
    {
        "Name": "home_default",
        "Id": "83bf606c51e50035e3d566124d24f12aafff33d825912e5672e104a203f00d00",
        "Created": "2023-10-07T05:39:57.307161694+02:00",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.25.0.0/16",
                    "Gateway": "172.25.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "4608090ea8b5bc7e32ad5f6b4858d1925510f29215484bf369d2e06f3f47ef3b": {
                "Name": "home-mosquitto-1",
                "EndpointID": "e1db2a3997076b9155b7e8dadb652357bcf2e5bc8e435591a76aedf98fcfd404",
                "MacAddress": "02:42:ac:19:00:02",
                "IPv4Address": "172.25.0.2/16",
                "IPv6Address": ""
            },
            "7e616599114992a7c4eaba4ddecc12ead0a8a16937fe205ca6ec721b761e7cd2": {
                "Name": "home-database-1",
                "EndpointID": "1e6b181e3580b3b92a0091ddacf8b2eb6adab9d3717c5e8bdb45d44b2090366f",
                "MacAddress": "02:42:ac:19:00:03",
                "IPv4Address": "172.25.0.3/16",
                "IPv6Address": ""
            },
            "81cf377d7d4487aecbdf309cfdfe46a97228f36a66a9aaeeadb727cb6c696ed1": {
                "Name": "home-grafana-1",
                "EndpointID": "7d35ce28a9e368ae3ea2902e56adbccfc2189fc17c95fbac70547edb85cadc10",
                "MacAddress": "02:42:ac:19:00:05",
                "IPv4Address": "172.25.0.5/16",
                "IPv6Address": ""
            },
            "b0b26dd1d1e09c20329f1195521467034e99cdcb5ed056cdaeacff4ad445d27d": {
                "Name": "home-teslamate-1",
                "EndpointID": "a3586239e3b8a3a0c9a598a46299d4242ba8d859bfb135f3143390a16d5485f2",
                "MacAddress": "02:42:ac:19:00:04",
                "IPv4Address": "172.25.0.4/16",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {
            "com.docker.compose.network": "default",
            "com.docker.compose.project": "home",
            "com.docker.compose.version": "2.21.0"
        }
    }
]
```
