### ISSUE TITLE
unable to change password

### ISSUE THREAD

**Issue by rodeho** [adriankumpf/teslamate#347]
Morning!

Somewhere in the dockerfile a variable is not processed well. When I change the default password to a custom one (just add an extra s). It wont work, and the DB container is reporting a user connecting with a wrong password.

From my first analysis it seems that the teslamate container is not changing the password when the password is changed at 3 locations in the docker compose file. Maybe an typo in the variable of the telsamate container, could we do a syntax check?

```YAML
services:
  teslamate:
    image: teslamate/teslamate:latest
    restart: always
    environment:
      - DATABASE_USER=teslamate
      - DATABASE_PASS=secret
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=db
      - MQTT_HOST=mosquitto
    ports:
      - 4000:4000
    cap_drop:
      - all
```
