### ISSUE TITLE
Cannot fetch MQTT for a hosted instance of Teslamate

### ISSUE THREAD

**Issue by gurmukhp** [adriankumpf/teslamate#3724]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I have Teslamate installed on a public server and it's protected using Basic Authentication as explained here: 
https://docs.teslamate.org/docs/guides/traefik

How can I set it so that the hosted Tesla Mate instance can publish to a locally hosted Home Assistant?

Thanks!

```
- sensor:
    name: Display Name
    object_id: tesla_display_name # entity_id
    unique_id: teslamate_1_display_name # internal id, used for device grouping
    availability: &teslamate_availability
      - topic: teslamate/cars/1/healthy
        payload_available: 'true'
        payload_not_available: 'false'
    device: &teslamate_device_info
      identifiers: [teslamate_car_1]
      configuration_url: https://username:password@teslamate.zxxz.io/
      manufacturer: Tesla
      model: Model 3
      name: Tesla Model 3
    state_topic: "teslamate/cars/1/display_name"
    icon: mdi:car
```

### Expected Behavior

.

### Steps To Reproduce

Restart HA

### Relevant log output

```shell
N/A
```

### Type of installation

Docker

### Version

v1.28.3
