### ISSUE TITLE
mosquitto.conf missing?

### ISSUE THREAD

**Issue by me1299** [adriankumpf/teslamate#439]
I'm struggling with a docker installation of Teslamate. First Grafana would not start up because of permissions errors. Turns out all files need to be owned by userid 472. Maybe add that to the manual, not sure how other people don't run into this?

Now the main problem, mosquitto container will not start. It keeps throwing the error:
```
1581367972: Error: Unable to open config file /mosquitto/config/mosquitto.conf.
```
I mounted the directory, but where do I obtain the config it should be using. Nowhere is there any mention of this file.

Relevant docker-compose.yml context:
```
  teslamate:
    container_name: teslamate    
    image: teslamate/teslamate:latest
    restart: always
    environment:
      - DATABASE_USER=teslamate
      - DATABASE_PASS=********
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=psql
      - MQTT_HOST=mosquitto
    volumes:
      - ${DOCKERDIR}/teslamate/base:/opt/app/import
    cap_drop:
      - all
    networks:
      - default
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.teslamate.entrypoints=http"
      - "traefik.http.routers.teslamate.middlewares=https-redirect@file"
      - "traefik.http.services.teslamate.loadbalancer.server.port=4000"
      - "traefik.http.routers.teslamate-secure.middlewares=traefik-auth"      
      - "traefik.http.routers.teslamate-secure.entrypoints=https"
      - "traefik.http.routers.teslamate-secure.tls=true"
      - "traefik.http.routers.teslamate-secure.service=teslamate"

  psql:
    container_name: psql
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_USER=teslamate
      - POSTGRES_PASSWORD=*******
      - POSTGRES_DB=teslamate
    volumes:
      - ${DOCKERDIR}/teslamate/db/:/var/lib/postgresql/data

  grafana:
    container_name: teslamate_grafana
    image: teslamate/grafana:latest
    restart: always
    environment:
      - DATABASE_USER=teslamate
      - DATABASE_PASS=********
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=psql
    ports:
      - 3000:3000
    volumes:
      - ${DOCKERDIR}/teslamate/grafana:/var/lib/grafana

  mosquitto:
    container_name: teslamate_mosquitto
    image: eclipse-mosquitto:1.6
    restart: always
    ports:
      - 1883:1883
    volumes:
      - ${DOCKERDIR}/teslamate/mosquitto-conf:/mosquitto/config
      - ${DOCKERDIR}/teslamate/mosquitto-data:/mosquitto/data
```
