### ISSUE TITLE
GUI to manage your docker installation: portrainer

### ISSUE THREAD

**Issue by DrMichael** [adriankumpf/teslamate#569]
**Is your feature request related to a problem? Please describe.**

This is not really a feature request, just a hint...

If you fancy a GUI to manage your docker installation, you could add the following to your docker-coompose.yml under the respective paragraphs:

```
services:
  portainer:
    image: portainer/portainer
    restart: always
    ports:
      - "9000:9000"
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:
```
And you get a decent GUI on port 9000.

**Describe the solution you'd like**

Perhaps worth a thought to include it in the standard docker-compose.yml, perhaps commented out.
