### ISSUE TITLE
Use parts of the docker-compose (without MQTT)

### ISSUE THREAD

**Issue by muster021** [adriankumpf/teslamate#594]
**Is your feature request related to a problem? Please describe.**

I already have a MQTT broker installed on the same host. It requires authentication and I do not know if there is an environment variable I can use to specify those. I've tried with
ENVIRONMENT=MQTT_USER=username
ENVIRONMENT=MQTT_PASSWORD=secret

without success.

**Describe the solution you'd like**

Can the documentation be updated with how you can add just:
1. Teslamate docker image (if you have everything else)
2. Teslamate, database
3. Teslamate, database, grafana
4. Teslamate, database, grafana and mqtt

**Describe alternatives you've considered**

Tried Google to find out what I dont know...

**Additional context**

**Comment by adriankumpf** [comment]
Did you change the `MQTT_HOST` variable as well? In general all variables prefixed with "MQTT_" (documented [here](https://docs.teslamate.org/docs/configuration/environment_variables) ) might be relevant if you want to use your own broker.

If you do not need a separate instance of Grafana/Mosquitto/Postgres as included in the sample docker-compose.yml, you can safely remove all service definitions but `teslamate` from the file.

**Comment by andrewfoster** [comment]
@muster021 Try using a docker compose file like this:

```
version: '3'
services:
  teslamate:
    image: teslamate/teslamate:latest
    restart: always
    environment:
      - MQTT_HOST=127.0.0.1
      - MQTT_USERNAME=username
      - MQTT_PASSWORD=secret
      # Rest of your config here ...
```
