### ISSUE TITLE
Home Assistant device_tracker always shows not_home

### ISSUE THREAD

**Issue by blysik** [adriankumpf/teslamate#695]
**Describe the bug**

The Home Assistant device_tracker never knows the car is home.  Even if proximity.home_tesla is 0, the device_tracker entities never show the car as home.

**Expected behavior**

If the car is parked at home, the device_tracker should say 'home'.

**How to reproduce it (as minimally and precisely as possible)**:
Normal usage.

 
**Environment**

- TeslaMate version: v.1.19.3
- Type of installation: Docker
- OS TeslaMate is installed on: Docker installed on Intel NUC, RHEL
- HA v0.109.4

**Comment by ngardiner** [comment]
The proximity sensor determines the distance between the zone (home) and the device-tracker specified. So if your config is:

```
proximity:
  home_tesla:
    zone: home
    devices:
      - device_tracker.tesla_location
    tolerance: 10
    unit_of_measurement: km
```

You can check:

- Does device_tracker.tesla_location correctly show the location of your vehicle on the map in lovelace
- Is the Home zone defined under zones with an accurate Lat and Lon value?

**Comment by blysik** [comment]
* I have that exact proximity block, yes.
* device_tracker.tesla_location does show the correct place on the map. 
* Home zone is defined correctly in the configuration.yaml, and in Configuration -> Zones -> Home -> the longitude/latitude are correct.

Everything appears correct, except the actual device_tracker always shows not_home.  It's super strange to me.  Maybe I should try deleting it?

See the attached image below.  (I covered the long/lat, but it's correct.)

<img width="862" alt="Screen Shot 2020-05-06 at 9 27 40 PM" src="https://user-images.githubusercontent.com/58610/81254818-0905a580-8fe1-11ea-81e3-4f93b0bb956d.png">

**Comment by ngardiner** [comment]
Yes I see what you're referring to and I have the same on my side.

I suspect that the state of the device tracker is updated by an automation and not by the lat and lon. I will do some research and get back to you, but I suspect there's an automation required to check if the device_tracker entity is within the home zone radius and if so to change status to home.

**Comment by blysik** [comment]
That seems reasonable.  I'll experiment with automations also and see if I can make something.  I was just under the expectation the logic was already there somehow.  Thanks.

**Comment by blysik** [comment]
My understanding is that this block will always set not_home:
```
- alias: Update Tesla location as MQTT location updates
  initial_state: true
  trigger:
  - platform: mqtt
    topic: teslamate/cars/1/latitude
  - platform: mqtt
    topic: teslamate/cars/1/longitude
  action:
  - service: device_tracker.see
    data_template:
      dev_id: tesla_location
      location_name: not_home
      gps:
      - '{{ states.sensor.tesla_latitude.state }}'
      - '{{ states.sensor.tesla_longitude.state }}'
```
Maybe the location needs to be a template, based on proximity.  If proximity 0, than home, if not, then not_home.

**Comment by blysik** [comment]
This automation seems to work for me properly.  Not sure if it's the most elegant method.

```
- alias: Update Tesla location as MQTT location updates
  initial_state: true
  trigger:
  - platform: mqtt
    topic: teslamate/cars/1/latitude
  - platform: mqtt
    topic: teslamate/cars/1/longitude
  action:
  - service: device_tracker.see
    data_template:
      dev_id: tesla_location
      location_name: >
            {% if is_state('proximity.home_tesla', '0') %}
              home
            {% else %}
              not_home
            {% endif %}
      gps:
      - '{{ states.sensor.tesla_latitude.state }}'
      - '{{ states.sensor.tesla_longitude.state }}'
```
