### ISSUE TITLE
Save user-chosen web app language

### ISSUE THREAD

**Issue by SDekkers** [adriankumpf/teslamate#711]
Currently the chosen language is saved in the users session, but after in a new session, the language is reverted back to the browser settings, or geo location?

**Comment by adriankumpf** [comment]
It uses your browser language by default but can be overridden on the settings page. Sessions are invalidated when restarting TeslaMate but there's an undocumented way to disable that: you can add the `SECRET_KEY_BASE` variable with a secret string. For example:

```YAML
   services:
     teslamate:
       environment:
         - SECRET_KEY_BASE=yourSecretKey

# ...
```
