### ISSUE TITLE
ERROR: No container found for database_1

### ISSUE THREAD

**Issue by injector22** [adriankumpf/teslamate#754]
I'm attempting to move my installation between hosts, I had an old version of yaml which used db instead of database but got around that issue with the foot note on the backup/restore page.

I spun up the container on the new host verified it works (didn't configure anything on the web page) and then spun it back down, I coped the teslamate.bck file between hosts and attempted to run the restore commands but received error "No container found for database_1"

![image](https://user-images.githubusercontent.com/5377979/82828971-34f9a580-9e80-11ea-96bd-e180a92a8b75.png)

not sure if the issue is related to the old vs new yaml or something else. I did update the container on the old host to the latest version and allowed the db jobs to finish before taking a backup.

**Comment by ntrandialpad** [comment]
The database has to be running for those commands to work. You also have to delete the database volume again since you initialized the app.

**Comment by tacotran** [comment]
The database container has to be running for those commands to work.

Since you initialized the app, you need to delete the database volume again.

**Comment by injector22** [comment]
So what should be correct procedure be for moving between hosts? Because if I follow the instructions it states to spin down the container, but with it stopped how would the database commands work? I tried moving my original (outdated) yml and running 

docker-compose exec -T db psql -U teslamate -d teslamate < teslamate.bck

but that complained with: No container found for db_1

Sorry for the trouble, just trying to figure out what the right process should be.

**Comment by tacotran** [comment]
So on your new machine,
```docker-compose stop
docker volume ls
```
You should see some identifier for your database volume

```docker volume rm _identifier_
docker-compose up -d database```

Then run the restore sequence.

**Comment by injector22** [comment]
Thanks, apparently I had an orphan container that was causing the issue. After running up and remove orphans the restore worked.

**Comment by DengineerPC** [comment]
Hi

I have the same issue.

Using Portainer and OMV5

Can you tell me what I am doing wrong please?

![image](https://user-images.githubusercontent.com/15641632/130445008-94a221a9-63d1-48c8-ac7e-5f45cdbd6063.png)

**Comment by stonecan** [comment]
I have a similar issue creating a backup on a portainer managed teslamate docker.

```
# docker-compose exec teslamate_database_1 pg_dump -U teslamate teslamate > backup_teslamate.bck

ERROR: No such service: teslamate_database_1
```

Been trying a few things mentioned before but nothing works. I'm at a loss.

**Comment by DrMichael** [comment]
It should probably be:
`docker-compose exec database pg_dump -U teslamate teslamate > backup_teslamate.bck
`

**Comment by stonecan** [comment]
> It should probably be:
> `docker-compose exec database pg_dump -U teslamate teslamate > backup_teslamate.bck`

Thanks, but still not working. I am quite certain that during a previous update of Teslamate using Portainer, new containers were created with '_1' names which is probably the cause of this issue but I can't find a way to undo this (and get my data backed up before I try anything). 
```
docker-compose exec database pg_dump -U teslamate teslamate > backup_teslamate.bck
ERROR: No container found for database_1
```

**Comment by DrMichael** [comment]
What is in your docker-compose.yml concerning the database?

**Comment by stonecan** [comment]
My docker-compose.yml:

```
version: "3"

services:
  teslamate:
    image: teslamate/teslamate:latest
    environment:
      - DATABASE_USER=teslamate
      - DATABASE_PASS=xxxx
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
      - MQTT_HOST=mosquitto
    volumes:
      - ./import:/opt/app/import
    cap_drop:
      - all
    ports:
      - 4000:4000
    restart: always

  database:
    image: postgres:13
    environment:
      - POSTGRES_USER=teslamate
      - POSTGRES_PASSWORD=xxxx
      - POSTGRES_DB=teslamate
    volumes:
      - teslamate-db:/var/lib/postgresql/data
    restart: always

  grafana:
    image: teslamate/grafana:latest
    environment:
      - DATABASE_USER=teslamate
      - DATABASE_PASS=xxxx
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
    volumes:
      - teslamate-grafana-data:/var/lib/grafana
    ports:
      - 3000:3000
    restart: always
    
  mosquitto:
    image: eclipse-mosquitto:2
    volumes:
      - mosquitto-conf:/mosquitto/config
      - mosquitto-data:/mosquitto/data
    ports:
      - 1883:1883
    command: mosquitto -c /mosquitto-no-auth.conf
    restart: always

volumes:
  teslamate-db:
  teslamate-grafana-data:
  mosquitto-conf:
  mosquitto-data:

```
