### ISSUE TITLE
database stuck in a restart loop - docker-entrypoint.sh: Permission denied

### ISSUE THREAD

**Issue by paulverket** [adriankumpf/teslamate#756]
**Describe the bug**

I've been running teslamate successfully for a while until today when I had to reboot the machine. The database was stuck in a restart loop. 

```
verket@pi3:~/Projects/teslaMateLocal$ sudo docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                            PORTS               NAMES
92928027e018        postgres:12         "docker-entrypoint.s…"   2 minutes ago       Restarting (126) 35 seconds ago                       teslamatelocal_db_1

```
The logs showed the problem:
```
verket@pi3:~/Projects/teslaMateLocal$ sudo docker logs --tail 50 --follow --timestamps 92928027e018
2020-05-26T00:52:27.740455484Z bash: /usr/local/bin/docker-entrypoint.sh: Permission denied
2020-05-26T00:52:34.780288596Z bash: /usr/local/bin/docker-entrypoint.sh: Permission denied

```
If I weren't such a Docker newbie I'd know how to fix this -- sorry.

I have a few db backups so I don't mind blowing things away and starting again. I tried to do that with a combination of:
```
sudo docker-compose  down
sudo docker-compose rm db
sudo docker volume rm ...
```

but still get the same problem when I do `sudo docker-compose up -d db`

**Environment**

- TeslaMate version: 1.19.3
- Type of installation: Docker 18.09.9
- OS TeslaMate is installed on: Ubuntu 19.10 (64 bit) on Raspberry pi 3
- User OS & Browser: Mac OS 10.15.4, Safari 13.1

Thanks in advance...
Paul

**Comment by paulverket** [comment]
Continued trying to fix the db looping issue by deleting everything:
```
sudo docker system prune -a
sudo docker volume prune
```

Downloading and running just the db continued with the restart loop.
`sudo docker-compose up -d db`

Docker 18.09.9 was installed as a snap. I'm debating whether I should remove it and install with apt-get.

**Comment by Dulanic** [comment]
If I had to guess it has something to do with your file permissions wherever your mounted volume location is. Can you post your docker-compose.yml? This question may need to move more to the postgresql docker area.

This is the script it's trying to run from within the container. https://github.com/docker-library/postgres/blob/master/12/docker-entrypoint.sh

**Comment by paulverket** [comment]
Tried removing and reinstalling docker from a snap: 
```
sudo snap remove docker
sudo snap install docker
```
Reran `sudo docker-compose up -d db` but still get restarts:
```
$ sudo docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED              STATUS                            PORTS               NAMES
4cfa46569cee        postgres:12         "docker-entrypoint.s…"   About a minute ago   Restarting (126) 18 seconds ago                       teslamatelocal_db_1
$ sudo docker logs --tail 50 --follow --timestamps 4cfa46569cee
2020-05-27T16:51:11.210201098Z bash: /usr/local/bin/docker-entrypoint.sh: Permission denied
2020-05-27T16:51:21.173613816Z bash: /usr/local/bin/docker-entrypoint.sh: Permission denied
```

Here's the docker-compose.yml file:
```
version: '3'

services:
  teslamate:
    image: teslamate/teslamate:latest
    restart: always
    environment:
      - DATABASE_USER=teslamate
      - DATABASE_PASS=xxx
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=db
      - MQTT_HOST=mosquitto
    ports:
      - 4000:4000
    volumes:
      - ./import:/opt/app/import
    cap_drop:
      - all

  db:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_USER=teslamate
      - POSTGRES_PASSWORD=xxx
      - POSTGRES_DB=teslamate
    volumes:
      - teslamate-db:/var/lib/postgresql/data

  grafana:
    image: teslamate/grafana:latest
    restart: always
    environment:
      - DATABASE_USER=teslamate
      - DATABASE_PASS=xxx
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=db
    ports:
      - 3000:3000
    volumes:
      - teslamate-grafana-data:/var/lib/grafana

  mosquitto:
    image: eclipse-mosquitto:1.6
    restart: always
    ports:
      - 1883:1883
    volumes:
      - mosquitto-conf:/mosquitto/config
      - mosquitto-data:/mosquitto/data

volumes:
    teslamate-db:
    teslamate-grafana-data:
    mosquitto-conf:
    mosquitto-data:
```

Thanks!
