### ISSUE TITLE
Teslamate not running on Synology DS713+

### ISSUE THREAD

**Issue by Benn** [adriankumpf/teslamate#765]
**Describe the bug**

After following the below guide on a DS713+ (with 2GB RAM) :
https://github.com/adriankumpf/teslamate/issues/113
Grafana on port 3000 is working fine, but Teslamate on port 4000 is not responding.
It works fine on both Raspberry Pis on which i installed it.

**Expected behavior**

when typing http://MyIP:4000, I should get the page to enter my Tesla credentials

**How to reproduce it (as minimally and precisely as possible)**:

1. Follow Synology install guide (with current docker-composer.yml)
2. open http://MyIP:4000

**Relevant entries from the logs**

Database_1 Logs : 

date | stream | content
-- | -- | --
2020-05-28 07:45:30 | stderr | 2020-05-28 07:45:30.732 UTC [1] LOG:  database system is ready to accept connections
2020-05-28 07:45:30 | stderr | 2020-05-28 07:45:30.709 UTC [63] LOG:  database system was shut down at 2020-05-28 07:45:30 UTC
2020-05-28 07:45:30 | stderr | 2020-05-28 07:45:30.649 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2020-05-28 07:45:30 | stderr | 2020-05-28 07:45:30.641 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2020-05-28 07:45:30 | stderr | 2020-05-28 07:45:30.641 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2020-05-28 07:45:30 | stderr | 2020-05-28 07:45:30.640 UTC [1] LOG:  starting PostgreSQL 12.3 (Debian 12.3-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
2020-05-28 07:45:30 | stdout |  
2020-05-28 07:45:30 | stdout | PostgreSQL init process complete; ready for start up.
2020-05-28 07:45:30 | stdout |  
2020-05-28 07:45:30 | stdout | server stopped
2020-05-28 07:45:30 | stdout | done
2020-05-28 07:45:30 | stdout | 2020-05-28 07:45:30.473 UTC [45] LOG:  database system is shut down
2020-05-28 07:45:30 | stdout | 2020-05-28 07:45:30.369 UTC [47] LOG:  shutting down
2020-05-28 07:45:30 | stdout | 2020-05-28 07:45:30.368 UTC [45] LOG:  background worker "logical replication launcher" (PID 52) exited with exit code 1
2020-05-28 07:45:30 | stdout | waiting for server to shut down....2020-05-28 07:45:30.360 UTC [45] LOG:  aborting any active transactions
2020-05-28 07:45:30 | stdout | 2020-05-28 07:45:30.355 UTC [45] LOG:  received fast shutdown request
2020-05-28 07:45:30 | stdout |  
2020-05-28 07:45:30 | stdout | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
2020-05-28 07:45:30 | stdout |  
2020-05-28 07:45:30 | stdout |  
2020-05-28 07:45:30 | stdout | CREATE DATABASE
2020-05-28 07:45:28 | stdout | server started
2020-05-28 07:45:28 | stdout | done
2020-05-28 07:45:28 | stdout | 2020-05-28 07:45:28.895 UTC [45] LOG:  database system is ready to accept connections
2020-05-28 07:45:28 | stdout | 2020-05-28 07:45:28.859 UTC [46] LOG:  database system was shut down at 2020-05-28 07:45:26 UTC
2020-05-28 07:45:28 | stdout | 2020-05-28 07:45:28.600 UTC [45] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2020-05-28 07:45:28 | stdout | waiting for server to start....2020-05-28 07:45:28.583 UTC [45] LOG:  starting PostgreSQL 12.3 (Debian 12.3-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
2020-05-28 07:45:28 | stderr | --auth-local and --auth-host, the next time you run initdb.
2020-05-28 07:45:28 | stderr | You can change this by editing pg_hba.conf or using the option -A, or
2020-05-28 07:45:28 | stderr | initdb: warning: enabling "trust" authentication for local connections
2020-05-28 07:45:28 | stdout |  
2020-05-28 07:45:28 | stdout | pg_ctl -D /var/lib/postgresql/data -l logfile start
2020-05-28 07:45:28 | stdout |  
2020-05-28 07:45:28 | stdout | Success. You can now start the database server using:
2020-05-28 07:45:28 | stdout |  
2020-05-28 07:45:28 | stdout |  
2020-05-28 07:45:28 | stdout | syncing data to disk ... ok
2020-05-28 07:45:26 | stdout | performing post-bootstrap initialization ... ok
2020-05-28 07:45:21 | stdout | running bootstrap script ... ok
2020-05-28 07:45:20 | stdout | creating configuration files ... ok
2020-05-28 07:45:20 | stdout | selecting default time zone ... Etc/UTC
2020-05-28 07:45:20 | stdout | selecting default shared_buffers ... 128MB
2020-05-28 07:45:20 | stdout | selecting default max_connections ... 100
2020-05-28 07:45:19 | stdout | selecting dynamic shared memory implementation ... posix
2020-05-28 07:45:19 | stdout | creating subdirectories ... ok
2020-05-28 07:45:19 | stdout | fixing permissions on existing directory /var/lib/postgresql/data ... ok
2020-05-28 07:45:19 | stdout |  
2020-05-28 07:45:19 | stdout | Data page checksums are disabled.
2020-05-28 07:45:19 | stdout |  
2020-05-28 07:45:19 | stdout | The default text search configuration will be set to "english".
2020-05-28 07:45:19 | stdout | The default database encoding has accordingly been set to "UTF8".
2020-05-28 07:45:19 | stdout | The database cluster will be initialized with locale "en_US.utf8".
2020-05-28 07:45:19 | stdout |  
2020-05-28 07:45:19 | stdout | This user must also own the server process.
2020-05-28 07:45:19 | stdout | The files belonging to this database system will be owned by user "postgres".

Teslamate_1 Logs :

2020-05-28 08:21:25 | stdout | waiting for postgres at database:5432 (1024sec)
2020-05-28 08:10:45 | stdout | waiting for postgres at database:5432 (512sec)
2020-05-28 08:04:22 | stdout | waiting for postgres at database:5432 (256sec)
2020-05-28 08:00:07 | stdout | waiting for postgres at database:5432 (128sec)
2020-05-28 07:56:56 | stdout | waiting for postgres at database:5432 (64sec)
2020-05-28 07:54:16 | stdout | waiting for postgres at database:5432 (32sec)
2020-05-28 07:51:53 | stdout | waiting for postgres at database:5432 (16sec)
2020-05-28 07:49:38 | stdout | waiting for postgres at database:5432 (8sec)
2020-05-28 07:47:27 | stdout | waiting for postgres at database:5432 (4sec)
2020-05-28 07:45:17 | stdout | waiting for postgres at database:5432 (2sec)

**Screenshots**

Screen recording of the install on a fresh Docker (after having completely deleted and reinstalled the docker package)
https://www.youtube.com/watch?v=sGRL6A-bSZQ

**Environment**

- TeslaMate version: 1.19.3 - 2020-05-03
- Type of installation: Docker
- OS TeslaMate is installed on: Synology Disk Station on DS713+ with 2MB RAM
- User OS & Browser: Windows / Chrome
- Others:

**Comment by dyxyl** [comment]
Which version of Docker do you have?

**Comment by Benn** [comment]
Docker version 18.09.8, build bfed4f5
--

**Comment by dyxyl** [comment]
It could be another broken version of the Docker package.

What is the output of the following two commands after starting the containers and waiting a while?
```
docker-compose exec teslamate nc -vvz -w 5 database 5432

docker-compose config
```
Even though it is a different problem, you could also try to downgrade Docker (see https://github.com/adriankumpf/teslamate/issues/108#issuecomment-526623459).

**Comment by bahree** [comment]
I am on the same version on Synology and this is working OK. 

From what I could gather from your video the only difference I caught was the explicit IP but it was too quick so I might be wrong. Here is my docker compose file if it helps.

```
version: '3'
services:
  teslamate:
    image: teslamate/teslamate:latest
    restart: always
    environment:
      - DATABASE_USER=teslamate
      - DATABASE_PASS=retracted
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
      - MQTT_HOST=mosquitto
      - VIRTUAL_HOST=192.168.10.2
      - TZ=America/Los_Angeles # (optional) replace to use local time in debug logs. See "Configuration".
    ports:
      - 4000:4000
    cap_drop:
      - all

  database:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_USER=teslamate
      - POSTGRES_PASSWORD=teslamate
      - POSTGRES_DB=teslamate
    ports:
      - 6432:5432
    volumes:
      - teslamate-db:/var/lib/postgresql/data

  grafana:
    image: teslamate/grafana:latest
    restart: always
    environment:
      - DATABASE_USER=teslamate
      - DATABASE_PASS=teslamate
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
    ports:
      - 4001:3000
    volumes:
      - teslamate-grafana-data:/var/lib/grafana

  mosquitto:
    image: eclipse-mosquitto:1.6
    restart: always
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - mosquitto-conf:/mosquitto/config
      - mosquitto-data:/mosquitto/data

volumes:
    teslamate-db:
    teslamate-grafana-data:
    mosquitto-conf:
    mosquitto-data:
```
