### ISSUE TITLE
Feature request: add basic auth for Grafana (port 3000) access

### ISSUE THREAD

**Issue by sbeaudette** [adriankumpf/teslamate#77]
First of all, great project, much appreciated.

Is it feasible to add some generic authentication, or OAuth (Google or GitHub) to the Grafana container?

I'm running on a cloud server.
For the teslamate container (port 4000), I can disable port 4000 immediately after entering my tesla credentials.  But I feel a little uncomfortable about leaving port 3000 open without any auth.

Thanks,
-Steve

**Comment by adriankumpf** [comment]
Thanks! Glad you like it.

When running on a cloud server, I would also feel very uncomfortable exposing grafana and/or teslamate to the internet. Especially with the default docker-compose config the database user used by grafana is not restricted to read access only. Also, the API tokens are stored in the database. Therefore, with the default setup the tokens could be retrieved through grafana. 

Personally, I would not want to rely on any authentication provided by grafana. So there are two options in my opinion:

1. don't publicly expose any port at all and instead use a VPN (e.g. wireguard) to connect to the server.
2. use a reverse-proxy that provides proper HTTPS and HTTP basic access authentication e.g. nginx or Traefik. The latter has everything built-in and requires a minimal config.

**Comment by Rfvgyhn** [comment]
I run behind a reverse proxy ([letsencrypt-companion](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion)) but grafana does support quite a few different [auth mechanisms](https://grafana.com/docs/auth/overview/). You can specify those options in your docker config as env vars.

**Comment by sbeaudette** [comment]
thanks for the ideas

**Comment by DrMichael** [comment]
How would _ set GF_AUTH_ANONYMOUS_ENABLED to false, so that Grafana only works with a valid login? And, btw, how could I add a user to Grafana? I am geeting "Permission denied", when trying that under admin...

**Comment by adriankumpf** [comment]
Add `GF_AUTH_ANONYMOUS_ENABLED` to the docker-compose file:

```yaml
  grafana:
    image: teslamate/grafana:latest
    environment:
      - DATABASE_USER=teslamate
      - DATABASE_PASS=secret
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=db
     - GF_AUTH_ANONYMOUS_ENABLED=false
    ports:
      - 3000:3000
    volumes:
      - teslamate-grafana-data:/var/lib/grafana
```

To create a new user login with the default admin user (password is `admin`) first.
